# Generated by Django 5.1.4 on 2024-12-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
    ]
